In [1]:
from Datos import Datos
from EstrategiaParticionado import *
from Clasificador import *
import numpy as np

In [7]:
dataset = Datos("ConjuntosDatos/german.data")
estrategia = ValidacionSimple()
clas = ClasificadorNaiveBayes()
val = clas.validacion(estrategia,dataset,clas)
media_error1 = np.mean(val)
desv_error1 = np.std(val)

print("Promedio del error = ", media_error1, "\nDesviación típica = ", desv_error1)

Promedio del error =  0.29400000000000004 
Desviación típica =  0.01786057109949175


In [8]:

    
#a = [1,2,3]
#print(np.zeros(3,4))
#print(normalizarDatos(a, calcularMediasDesv(a)))


for i in range(len(estrategia.particiones)):
#medias = {}
    medias = dataset.calcularMediasDesv(dataset.extraeDatos(estrategia.particiones[i].indicesTrain))


print(dataset.normalizarDatos(dataset.datos))

[[-1.226 -1.242  1.352 ...  1.237 -0.204 -0.639]
 [-0.433  2.33  -0.485 ... -0.808 -0.204  1.564]
 [ 1.155 -0.732  1.352 ... -0.808 -0.204 -0.639]
 ...
 [ 1.155 -0.732 -0.485 ... -0.808 -0.204 -0.639]
 [-1.226  2.075 -0.485 ...  1.237 -0.204  1.564]
 [-0.433  2.075  1.352 ... -0.808 -0.204 -0.639]]
