In [1]:
from Datos import Datos
from EstrategiaParticionado import *
from Clasificador import *
from ClasificadorAG import *
import numpy as np

In [2]:
dataset = Datos("ConjuntosDatos/example1.data")

In [3]:
n_cromosomas = 10
n_generaciones = 5

ag = ClasificadorAG(n_cromosomas, dataset, n_generaciones, regla_entera = True)

In [8]:
print(dataset.a)
print(dataset.k)
print(ag.datosIntervalizados)

[0.9608027142857143, 0.3940834285714286]
7
[[4. 4. 0.]
 [3. 3. 0.]
 [4. 4. 0.]
 ...
 [5. 4. 1.]
 [3. 5. 1.]
 [3. 5. 1.]]


In [ ]:
import math
columns = np.column_stack(dataset.datos)
datosIntervalos = np.zeros((len(columns)-1, len(dataset.datos))) #Dos parentesis, tiene que ser un shape
mins = []

for row in columns[:-1]: #Necesito los minimos de cada atributo
    mins.append(np.amin(row))
print(mins)
for i, (fila_inter, col, a, col_min) in enumerate(zip(datosIntervalos, columns[:-1], dataset.a, mins)): #Itero sobre los datos correspondientes a las columnas
    
    for j,(attr_inter, dato) in enumerate(zip(fila_inter, col)): #por cada valor de la fila, uso el minimo de ese atributo y el "a" de ese atributo
        fila_inter[j] = math.ceil((dato - col_min)/a)
# for i in range(len(columns)-1):
#     v_min = np.amin(columns[i])
#     for j in range(len(datos)):
#         datosIntervalos[i][j] = math.ceil((columns[i][j] - mins[j])/self.a[j])
print(columns[-1])
print(np.column_stack(datosIntervalos.tolist() + [columns[-1]]))