In [1]:
from Datos import Datos
from EstrategiaParticionado import *
from Clasificador import *
import numpy as np
#from tabulate import tabulate


In [2]:
dataset = Datos("ConjuntosDatos/balloons.data")
estrategiaS = ValidacionSimple('ValidacionSimple', 5, 0.5, dataset)
print("Estrategia Validacion Simple:")
for i in estrategiaS.particiones.keys():
    # print("test: ", estrategiaS.particiones[i].indicesTest)
    # print("train: ", estrategiaS.particiones[i].indicesTrain)
    clas = ClasificadorNaiveBayes()

    clas.entrenamiento(dataset.extraeDatos(range(len(dataset.datos))), dataset.tipoAtributos, dataset.diccionarios)
    print(clas.probabilidades)
    #print(np.column_stack(dataset.extraeDatos(range(950)))[-1])
    clas.clasifica(dataset.extraeDatos(range(len(dataset.datos))), dataset.tipoAtributos, dataset.diccionarios)
    print("\n")

Estrategia Validacion Simple:
[{0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]


[{0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]


[{0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]


[{0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]


[{0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]




In [3]:
dataset = Datos("ConjuntosDatos/balloons.data")
estrategiaS = ValidacionSimple('ValidacionSimple', 5, 0.3, dataset)
clas = ClasificadorNaiveBayes()



print (dataset.datos[:5])
#for i in estrategiaS.particiones.keys():
print("test: ", estrategiaS.particiones[0].indicesTest)
print("train: ", estrategiaS.particiones[0].indicesTrain)
clas.entrenamiento(dataset.datos[:5], dataset.tipoAtributos, dataset.diccionarios)
print(clas.probabilidades)




[[1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 1. 0.]]
test:  [13  7 16 18  3  0 15  5 11  6 10  8  1 14]
train:  [12  2 19  4  9 17]
[{0: {0: 0.0, 1: 0.0}, 1: {0: 1.0, 1: 1.0}}, {0: {0: 0.0, 1: 0.0}, 1: {0: 1.0, 1: 1.0}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]


In [4]:
prueba = []
prueba = clas.clasificaP(dataset.datos[:5], dataset.tipoAtributos, dataset.diccionarios)
print(prueba)

0 0.6 [0.6, 0.4]
{0: 0.6}
0 0.6 [0.6, 0.4]
{0: 0.6}
0 1.0 [1.0, 0.0]
{0: 1.0}
1 0.67 [0.33, 0.67]
{1: 0.67}
1 0.67 [0.33, 0.67]
{1: 0.67}
0 1.0 [1.0, 0.0]
{0: 1.0}
[{}, {0: 0.6}, {}, {0: 0.6}, {0: 1.0}, {1: 0.67}, {1: 0.67}, {0: 1.0}]


In [5]:
dataset = Datos("ConjuntosDatos/balloons.data")
estrategiaS = ValidacionSimple('ValidacionSimple', 5, 0.3, dataset)
clas = ClasificadorNaiveBayes(laplace = True)



print (dataset.datos[:5])
#for i in estrategiaS.particiones.keys():
print("test: ", estrategiaS.particiones[0].indicesTest)
print("train: ", estrategiaS.particiones[0].indicesTrain)
clas.entrenamiento(dataset.datos[:5], dataset.tipoAtributos, dataset.diccionarios)
print(clas.probabilidades)

[[1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 1. 0.]]
test:  [ 5  9  2 14 13 11 12  6  8 15  3  4  1 10]
train:  [19  7 17 16 18  0]
[{0: {0: 0.25, 1: 0.33}, 1: {0: 1.0, 1: 1.0}}, {0: {0: 0.25, 1: 0.33}, 1: {0: 1.0, 1: 1.0}}, {0: {0: 0.75, 1: 0.33}, 1: {0: 0.5, 1: 1.0}}, {0: {0: 0.5, 1: 1.0}, 1: {0: 0.75, 1: 0.33}}]


In [ ]:
a = [1, 2, 3, 5]
print(sum(a))

In [ ]:
a = {'h' : 10, 'z':4}
for key in a:
    a[key] += 1
print(a)