In [1]:
from Datos import Datos
from EstrategiaParticionado import *
from Clasificador import *
import numpy as np
#from tabulate import tabulate


In [2]:
dataset = Datos("ConjuntosDatos/balloons.data")
estrategiaS = ValidacionSimple('ValidacionSimple', 5, 0.5, dataset)
print("Estrategia Validacion Simple:")
for i in estrategiaS.particiones.keys():
    # print("test: ", estrategiaS.particiones[i].indicesTest)
    # print("train: ", estrategiaS.particiones[i].indicesTrain)
    clas = ClasificadorNaiveBayes()

    clas.entrenamiento(dataset.extraeDatos(range(len(dataset.datos))), dataset.tipoAtributos, dataset.diccionarios)
    print(clas.probabilidades)
    #print(np.column_stack(dataset.extraeDatos(range(950)))[-1])
    clas.clasifica(dataset.extraeDatos(range(len(dataset.datos))), dataset.tipoAtributos, dataset.diccionarios)
    print("\n")

Estrategia Validacion Simple:
[{0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]


[{0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]


[{0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]


[{0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]


[{0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1: 0.5}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]




In [3]:
dataset = Datos("ConjuntosDatos/balloons.data")
estrategiaS = ValidacionSimple('ValidacionSimple', 5, 0.3, dataset)
clas = ClasificadorNaiveBayes()



print (dataset.datos[:5])
#for i in estrategiaS.particiones.keys():
print("test: ", estrategiaS.particiones[0].indicesTest)
print("train: ", estrategiaS.particiones[0].indicesTrain)
clas.entrenamiento(dataset.datos[:5], dataset.tipoAtributos, dataset.diccionarios)
print(clas.probabilidades)




[[1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 1. 0.]]
test:  [12 13  4 18 17  9  3  0 16 19 10  2  7 11]
train:  [14  5  1  6  8 15]
[{0: {0: 0.0, 1: 0.0}, 1: {0: 1.0, 1: 1.0}}, {0: {0: 0.0, 1: 0.0}, 1: {0: 1.0, 1: 1.0}}, {0: {0: 0.67, 1: 0.0}, 1: {0: 0.33, 1: 1.0}}, {0: {0: 0.33, 1: 1.0}, 1: {0: 0.67, 1: 0.0}}]


In [4]:
prueba = {}
prueba = clas.clasificaP(dataset.datos[:5], dataset.tipoAtributos, dataset.diccionarios)


0 0.6 [0.6, 0.4]
0 0.6 [0.6, 0.4]
0 1.0 [1.0, 0.0]
1 0.67 [0.33, 0.67]
1 0.67 [0.33, 0.67]
0 1.0 [1.0, 0.0]


In [ ]:
def clasifica(datostest,atributosDiscretos,diccionario):
    columns = np.column_stack(datostrain)
    c, counts = np.unique(columns[-1], return_counts=True)
    p_class = dict(zip(c.astype(int), counts))
    ini_clas = dict.fromkeys(np.unique(columns[-1]).astype(int), 0)

    probabilidades = []
    clas = columns[-1]

    for key in diccionario:
        if key != "Class":
            prob_clas = {}
            for value in diccionario[key]:
                prob_clas.update({int(diccionario[key][value]):ini_clas.copy()})
            probabilidades.append(prob_clas)
    for index_col in range(len(columns[:-1])):
        
        if atributosDiscretos[index_col] == "Nominal":
            for i in range(len(columns[index_col])):      
            
            for value in probabilidades[index_col]:                
                evidencia = sum(probabilidades[index_col][value].values()) / len(columns[index_col])
                for i in probabilidades[index_col][value]:
                    verosimilitud = probabilidades[index_col][value][i] / p_class[i]
                    prior = p_class[i] / len(columns[index_col])
                    
                    if (evidencia > 0):
                        probabilidades[index_col][value][i] = round((verosimilitud * prior) / evidencia, 2)

    return probabilidades

In [ ]:
a = [1, 2, 3, 5]
print(sum(a))